apiVersion: v1
kind: ConfigMap
metadata:
  name: api-users
  labels:
    app: activemq-artemis-jolokia-api-server
data:
  users.json: |
    {
      "users": [
        {
          "id": "admin",
          "hash": "$2a$15$deBI0sO4Cvn2gr/QA5pju.94Klh377Np.mcYteBgYlQuyeIwyK4UK"
        }
      ]
    }
